version: '3.9'

services:
  jarvis-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jarvis-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./models:/app/models
    environment:
      - COQUI_TOS_AGREED=1
    restart: unless-stopped
